### ISSUE TITLE
Symlink documentation is either wrong or the wording is confusing

### ISSUE THREAD

**Issue by njbmartin** [akamai/NetStorageKit-Node#6]
### symlink
*[↑ back to method list](#methods)*
- **Syntax**: 
```Javascript
ns.symlink(NETSTORAGE_TARGET, NETSTORAGE_DESTINATION, callback(err, response, body))
```
- **Parameters**:

| Name        | Type        | Description                     |
| :---------- | :---------: | :------------------------------ |
| `NETSTORAGE_TARGET` | *string* | full path of the symlink to create |
| `NETSTORAGE_DESTINATION` | *string* | full path to file to symlink to |

At first glance of the descriptions, target is where you want the symlink to be created and destination is where you want the symlink to point to.

It should probably be:

| Name        | Type        | Description                     |
| :---------- | :---------: | :------------------------------ |
| `NETSTORAGE_TARGET` | *string* | full path of the original file/folder |
| `NETSTORAGE_DESTINATION` | *string* | full path of the intended symlink |

**Comment by AstinCHOI** [comment]
Thank you, Merged it.
